services:
  core-service:
    build:
      context: .
    ports:
      - "3001:3001"
    container_name: core-service
    restart: on-failure
    environment:
      PG_DSN: ${PG_DSN}
      APP_DOMAIN: max_home